# Generated by Django 3.0.6 on 2020-07-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200704_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Sno',
            new_name='sno',
        ),
    ]
