# Generated by Django 3.0.6 on 2020-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.CharField(default=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
