# Generated by Django 3.0.6 on 2020-07-02 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=130),
            preserve_default=False,
        ),
    ]
