# Generated by Django 3.0.6 on 2020-07-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
